# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: warehouse.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'warehouse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\"|\n\x0bProductData\x12\x11\n\tproductID\x18\x01 \x01(\t\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x17\n\x0fproductCategory\x18\x03 \x01(\t\x12\x17\n\x0fproductQuantity\x18\x04 \x01(\x05\x12\x13\n\x0bproductUnit\x18\x05 \x01(\t\"\xc2\x01\n\rWarehouseData\x12\x13\n\x0bwarehouseID\x18\x01 \x01(\t\x12\x18\n\x10warehouseAddress\x18\x02 \x01(\t\x12\x1b\n\x13warehousePostalCode\x18\x03 \x01(\t\x12\x15\n\rwarehouseCity\x18\x04 \x01(\t\x12\x18\n\x10warehouseCountry\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12!\n\x0bproductData\x18\x08 \x03(\x0b\x32\x0c.ProductData\"0\n\rStoreResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tisSuccess\x18\x02 \x01(\x08\x32\x44\n\x10WarehouseService\x12\x30\n\x0estoreWarehouse\x12\x0e.WarehouseData\x1a\x0e.StoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTDATA']._serialized_start=19
  _globals['_PRODUCTDATA']._serialized_end=143
  _globals['_WAREHOUSEDATA']._serialized_start=146
  _globals['_WAREHOUSEDATA']._serialized_end=340
  _globals['_STORERESPONSE']._serialized_start=342
  _globals['_STORERESPONSE']._serialized_end=390
  _globals['_WAREHOUSESERVICE']._serialized_start=392
  _globals['_WAREHOUSESERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
